### ISSUE TITLE
Amount of token locked in a tick

### ISSUE THREAD

**Issue by sydneyhenrard** [chunza2542/uniswapv3-calculator#5]
Do you know how the amount of token locked in a tick is calculated?

We can see this information in the histogram from Uniswap
https://info.uniswap.org/#/pools/0xd0fc8ba7e267f2bc56044a7715a489d851dc6d78 

![image](https://user-images.githubusercontent.com/5309640/130325416-bb2f9324-ffc3-42cd-a8c1-619e9818773b.png)

Thanks for your app which is useful to see how much fees one can earn.

**Comment by chunza2542** [comment]
@sydneyhenrard It depends on how much size of a range between 2 ticks is, for calculation, you can use `Tick.liquidityNet` to calculate the total amount of liquidity locked between the two and you need to convert the result into a token amount. (because the liquidity is calculated from `L = sqrt(x * y)`)
